To/#137 convert grid
ie3-institute/powerFactory2psdm pull request #141
Opened 2021-10-28 12:08 UTC by t-ober

Resolves #137 and #131

2021-11-18 11:02 UTC, sebastian-peter requested changes
lgtm mostly, there's only some minor stuff surrounding `StaticGeneratorConverter`

2021-11-18 15:58 UTC, t-ober commented on src/main/scala/edu/ie3/powerFactory2psdm/converter/StaticGeneratorConverter.scala
> +            WecInputGenerator.generate(statGen, node, modelGeneration)
fair

2021-11-18 15:58 UTC, t-ober commented on src/main/scala/edu/ie3/powerFactory2psdm/converter/StaticGeneratorConverter.scala
> +  ): Any = {
enough

2021-11-29 10:30 UTC, sebastian-peter approved these changes

2021-11-29 10:30 UTC, merged