Handle line sections
ie3-institute/powerFactory2psdm pull request #157
Opened 2021-11-24 12:53 UTC by t-ober

2021-11-26 07:07 UTC, t-ober commented
!test

2021-12-21 19:22 UTC, sebastian-peter requested changes
looks mostly good to me, just some small suggestions

2021-12-21 19:22 UTC, sebastian-peter commented on src/main/scala/edu/ie3/powerFactory2psdm/model/entity/LineSection.scala
> +  def getLineId(lineSectionId: String): String = {
```suggestion
  private def getLineId(lineSectionId: String): String = {
```

2021-12-21 19:22 UTC, sebastian-peter commented on src/main/scala/edu/ie3/powerFactory2psdm/model/entity/LineSection.scala
> +        s"There is no defined type line section $id"
```suggestion
        s"There is no defined type for line section $id"
```

2021-12-22 09:55 UTC, sebastian-peter commented
Oh and btw, I think it would make sense to note these additions and changes in `CHANGELOG.md`

2021-12-29 09:07 UTC, t-ober commented on src/main/scala/edu/ie3/powerFactory2psdm/converter/LineConverter.scala
> +      }
I think you can do it both ways. I would rather keep it here as this logic is mostly about determining if this is a line with line sections for which we still have to do the conversion for and its not only about retrieving the corresponding line type from the line type mapping.

2021-12-29 09:11 UTC, t-ober commented on src/main/scala/edu/ie3/powerFactory2psdm/converter/LineConverter.scala
> +      }
Tbh having different locations where we convert line types is not optimal but has to do with the way our powerfactory grid data is organized. I will document that a little more and then I think this is fine.

2022-01-04 13:40 UTC, sebastian-peter approved these changes

2022-01-04 13:46 UTC, merged