To/#178 custom node uuids
ie3-institute/powerFactory2psdm pull request #180
Opened 2022-01-11 16:38 UTC by t-ober

Resolves #178

2022-01-14 12:18 UTC, sebastian-peter commented
@t-ober going to review soon, for now you could consider solving the code smells already

2022-02-10 11:16 UTC, sebastian-peter commented on src/main/scala/edu/ie3/powerFactory2psdm/converter/NodeConverter.scala
> +      unsafeNodeId2Uuid: Map[String, UUID]
Specify in ScalaDoc

2022-02-10 11:16 UTC, sebastian-peter commented on src/main/scala/edu/ie3/powerFactory2psdm/converter/NodeConverter.scala
> +      unsafeNodeId2Uuid: Map[String, UUID]
Specify in ScalaDoc

2022-02-10 11:17 UTC, sebastian-peter commented on src/main/scala/edu/ie3/powerFactory2psdm/converter/NodeConverter.scala
> +      shortNodeId2Uuid: Map[String, UUID]
Why choose a different name for the map here than above?

Also, specify in ScalaDoc

2022-02-10 11:21 UTC, sebastian-peter commented on src/main/scala/edu/ie3/powerFactory2psdm/converter/NodeConverter.scala
> +              )
Include caught exception when throwing new exception 

```suggestion
              throw new IllegalArgumentException(
                s"UUID: $uuidString on line: $line is not a valid UUID.",
                exception
              )
```

2022-02-10 11:25 UTC, sebastian-peter commented on src/main/scala/edu/ie3/powerFactory2psdm/converter/NodeConverter.scala
> +    val duplicateIds = ConversionHelper.getDuplicates(ids)
I like that you're checking the input here. Duplicate keys would just get eliminated when calling `.toMap`

2022-02-10 11:43 UTC, sebastian-peter commented on src/main/scala/edu/ie3/powerFactory2psdm/model/PreprocessedPfGridModel.scala
> +      ConversionHelper.getDuplicates(rawNodes.map(_.locName).toVector)
Unnecessary conversion

```suggestion
      ConversionHelper.getDuplicates(rawNodes.map(_.locName))
```

2022-02-10 11:43 UTC, sebastian-peter commented on src/main/scala/edu/ie3/powerFactory2psdm/model/PreprocessedPfGridModel.scala
> +    val duplicateIds = ConversionHelper.getDuplicates(modelIds.toVector)
Unnecessary conversion

```suggestion
    val duplicateIds = ConversionHelper.getDuplicates(modelIds)
```

2022-02-10 11:52 UTC, sebastian-peter commented on src/main/scala/edu/ie3/powerFactory2psdm/converter/NodeConverter.scala
> +    nodeId2Uuid
Why not like this?
```suggestion
    bufferedSource.close
    idsAndUuids.toMap
```

2022-02-12 14:22 UTC, t-ober commented on build.gradle
> +	implementation 'tech.units:indriya:2.1.3-SNAPSHOT'
yes this is needed due to an issue with a comparison that is only fixed in their current snapshot release https://github.com/unitsofmeasurement/indriya/issues/362

2022-02-12 14:23 UTC, t-ober commented on src/test/resources/corrupt_id_mapping.csv
> +uuid;id
since there are not many test ressources right now I don't think this is neccessary

2022-02-12 14:24 UTC, t-ober commented on src/test/scala/edu/ie3/powerFactory2psdm/converter/NodeConverterSpec.scala
> +          throw TestException("Map does not contain the given key.")
oh nice

2022-02-12 14:36 UTC, t-ober commented on src/main/scala/edu/ie3/powerFactory2psdm/converter/types/LineTypeConverter.scala
> +      case _ if abs(aggregatedLineSectionLength / lineLength - 1) < 1e-6 =>
Not sure if this is neccessary as I don't use it at any other place anyways and I don't think it enhances readability or helps in any other way. Feel free to push back.

2022-02-14 13:23 UTC, sebastian-peter requested changes

2022-02-14 13:23 UTC, sebastian-peter commented on src/main/scala/edu/ie3/powerFactory2psdm/converter/GridConverter.scala
> +import java.io.IOException
There's a bunch of unused imports here. Would you mind removing them? Then this is good to go

2022-02-15 21:49 UTC, sebastian-peter approved these changes

2022-02-16 07:34 UTC, merged